/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class AArComandoSemCasamAComando extends PAComando
{
    private PAComandoSemCasam _aComandoSemCasam_;

    public AArComandoSemCasamAComando()
    {
        // Constructor
    }

    public AArComandoSemCasamAComando(
        @SuppressWarnings("hiding") PAComandoSemCasam _aComandoSemCasam_)
    {
        // Constructor
        setAComandoSemCasam(_aComandoSemCasam_);

    }

    @Override
    public Object clone()
    {
        return new AArComandoSemCasamAComando(
            cloneNode(this._aComandoSemCasam_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArComandoSemCasamAComando(this);
    }

    public PAComandoSemCasam getAComandoSemCasam()
    {
        return this._aComandoSemCasam_;
    }

    public void setAComandoSemCasam(PAComandoSemCasam node)
    {
        if(this._aComandoSemCasam_ != null)
        {
            this._aComandoSemCasam_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aComandoSemCasam_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._aComandoSemCasam_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._aComandoSemCasam_ == child)
        {
            this._aComandoSemCasam_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._aComandoSemCasam_ == oldChild)
        {
            setAComandoSemCasam((PAComandoSemCasam) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
