/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class TVetorUnidimensional extends Token
{
    public TVetorUnidimensional(String text)
    {
        setText(text);
    }

    public TVetorUnidimensional(String text, int line, int pos)
    {
        setText(text);
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TVetorUnidimensional(getText(), getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTVetorUnidimensional(this);
    }
}
