/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class TLer extends Token
{
    public TLer()
    {
        super.setText("ler");
    }

    public TLer(int line, int pos)
    {
        super.setText("ler");
        setLine(line);
        setPos(pos);
    }

    @Override
    public Object clone()
    {
      return new TLer(getLine(), getPos());
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseTLer(this);
    }

    @Override
    public void setText(@SuppressWarnings("unused") String text)
    {
        throw new RuntimeException("Cannot change TLer text.");
    }
}
