/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class AAdicaoSubtracaoExpCmp extends PExpCmp
{
    private PExpCmp _expCmp_;
    private PMaisMenos _maisMenos_;
    private PExpTermo _expTermo_;

    public AAdicaoSubtracaoExpCmp()
    {
        // Constructor
    }

    public AAdicaoSubtracaoExpCmp(
        @SuppressWarnings("hiding") PExpCmp _expCmp_,
        @SuppressWarnings("hiding") PMaisMenos _maisMenos_,
        @SuppressWarnings("hiding") PExpTermo _expTermo_)
    {
        // Constructor
        setExpCmp(_expCmp_);

        setMaisMenos(_maisMenos_);

        setExpTermo(_expTermo_);

    }

    @Override
    public Object clone()
    {
        return new AAdicaoSubtracaoExpCmp(
            cloneNode(this._expCmp_),
            cloneNode(this._maisMenos_),
            cloneNode(this._expTermo_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAdicaoSubtracaoExpCmp(this);
    }

    public PExpCmp getExpCmp()
    {
        return this._expCmp_;
    }

    public void setExpCmp(PExpCmp node)
    {
        if(this._expCmp_ != null)
        {
            this._expCmp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expCmp_ = node;
    }

    public PMaisMenos getMaisMenos()
    {
        return this._maisMenos_;
    }

    public void setMaisMenos(PMaisMenos node)
    {
        if(this._maisMenos_ != null)
        {
            this._maisMenos_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._maisMenos_ = node;
    }

    public PExpTermo getExpTermo()
    {
        return this._expTermo_;
    }

    public void setExpTermo(PExpTermo node)
    {
        if(this._expTermo_ != null)
        {
            this._expTermo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expTermo_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expCmp_)
            + toString(this._maisMenos_)
            + toString(this._expTermo_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expCmp_ == child)
        {
            this._expCmp_ = null;
            return;
        }

        if(this._maisMenos_ == child)
        {
            this._maisMenos_ = null;
            return;
        }

        if(this._expTermo_ == child)
        {
            this._expTermo_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expCmp_ == oldChild)
        {
            setExpCmp((PExpCmp) newChild);
            return;
        }

        if(this._maisMenos_ == oldChild)
        {
            setMaisMenos((PMaisMenos) newChild);
            return;
        }

        if(this._expTermo_ == oldChild)
        {
            setExpTermo((PExpTermo) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
