/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class AArBooleanoATipoBase extends PATipoBase
{
    private TBaseBooleano _baseBooleano_;

    public AArBooleanoATipoBase()
    {
        // Constructor
    }

    public AArBooleanoATipoBase(
        @SuppressWarnings("hiding") TBaseBooleano _baseBooleano_)
    {
        // Constructor
        setBaseBooleano(_baseBooleano_);

    }

    @Override
    public Object clone()
    {
        return new AArBooleanoATipoBase(
            cloneNode(this._baseBooleano_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArBooleanoATipoBase(this);
    }

    public TBaseBooleano getBaseBooleano()
    {
        return this._baseBooleano_;
    }

    public void setBaseBooleano(TBaseBooleano node)
    {
        if(this._baseBooleano_ != null)
        {
            this._baseBooleano_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._baseBooleano_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._baseBooleano_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._baseBooleano_ == child)
        {
            this._baseBooleano_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._baseBooleano_ == oldChild)
        {
            setBaseBooleano((TBaseBooleano) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
