/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import java.util.*;
import caju.analysis.*;

@SuppressWarnings("nls")
public final class AArListaNomesAListaNomes extends PAListaNomes
{
    private TId _id_;
    private final LinkedList<PAVirgulaId> _aVirgulaId_ = new LinkedList<PAVirgulaId>();

    public AArListaNomesAListaNomes()
    {
        // Constructor
    }

    public AArListaNomesAListaNomes(
        @SuppressWarnings("hiding") TId _id_,
        @SuppressWarnings("hiding") List<?> _aVirgulaId_)
    {
        // Constructor
        setId(_id_);

        setAVirgulaId(_aVirgulaId_);

    }

    @Override
    public Object clone()
    {
        return new AArListaNomesAListaNomes(
            cloneNode(this._id_),
            cloneList(this._aVirgulaId_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArListaNomesAListaNomes(this);
    }

    public TId getId()
    {
        return this._id_;
    }

    public void setId(TId node)
    {
        if(this._id_ != null)
        {
            this._id_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._id_ = node;
    }

    public LinkedList<PAVirgulaId> getAVirgulaId()
    {
        return this._aVirgulaId_;
    }

    public void setAVirgulaId(List<?> list)
    {
        for(PAVirgulaId e : this._aVirgulaId_)
        {
            e.parent(null);
        }
        this._aVirgulaId_.clear();

        for(Object obj_e : list)
        {
            PAVirgulaId e = (PAVirgulaId) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._aVirgulaId_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._id_)
            + toString(this._aVirgulaId_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._id_ == child)
        {
            this._id_ = null;
            return;
        }

        if(this._aVirgulaId_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._id_ == oldChild)
        {
            setId((TId) newChild);
            return;
        }

        for(ListIterator<PAVirgulaId> i = this._aVirgulaId_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PAVirgulaId) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
