/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class AArListaExpVazioAListaExp extends PAListaExp
{

    public AArListaExpVazioAListaExp()
    {
        // Constructor
    }

    @Override
    public Object clone()
    {
        return new AArListaExpVazioAListaExp();
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArListaExpVazioAListaExp(this);
    }

    @Override
    public String toString()
    {
        return "";
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        throw new RuntimeException("Not a child.");
    }
}
