/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class AArStringAExp extends PAExp
{
    private TVetorUnidimensional _vetorUnidimensional_;

    public AArStringAExp()
    {
        // Constructor
    }

    public AArStringAExp(
        @SuppressWarnings("hiding") TVetorUnidimensional _vetorUnidimensional_)
    {
        // Constructor
        setVetorUnidimensional(_vetorUnidimensional_);

    }

    @Override
    public Object clone()
    {
        return new AArStringAExp(
            cloneNode(this._vetorUnidimensional_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArStringAExp(this);
    }

    public TVetorUnidimensional getVetorUnidimensional()
    {
        return this._vetorUnidimensional_;
    }

    public void setVetorUnidimensional(TVetorUnidimensional node)
    {
        if(this._vetorUnidimensional_ != null)
        {
            this._vetorUnidimensional_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._vetorUnidimensional_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._vetorUnidimensional_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._vetorUnidimensional_ == child)
        {
            this._vetorUnidimensional_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._vetorUnidimensional_ == oldChild)
        {
            setVetorUnidimensional((TVetorUnidimensional) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
