/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class AArSenaoAComandoCasam extends PAComandoCasam
{
    private PAExp _aExp_;
    private PAComandoSemCasam _aComandoSemCasam_;
    private PAComandoCasam _aComandoCasam_;

    public AArSenaoAComandoCasam()
    {
        // Constructor
    }

    public AArSenaoAComandoCasam(
        @SuppressWarnings("hiding") PAExp _aExp_,
        @SuppressWarnings("hiding") PAComandoSemCasam _aComandoSemCasam_,
        @SuppressWarnings("hiding") PAComandoCasam _aComandoCasam_)
    {
        // Constructor
        setAExp(_aExp_);

        setAComandoSemCasam(_aComandoSemCasam_);

        setAComandoCasam(_aComandoCasam_);

    }

    @Override
    public Object clone()
    {
        return new AArSenaoAComandoCasam(
            cloneNode(this._aExp_),
            cloneNode(this._aComandoSemCasam_),
            cloneNode(this._aComandoCasam_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAArSenaoAComandoCasam(this);
    }

    public PAExp getAExp()
    {
        return this._aExp_;
    }

    public void setAExp(PAExp node)
    {
        if(this._aExp_ != null)
        {
            this._aExp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aExp_ = node;
    }

    public PAComandoSemCasam getAComandoSemCasam()
    {
        return this._aComandoSemCasam_;
    }

    public void setAComandoSemCasam(PAComandoSemCasam node)
    {
        if(this._aComandoSemCasam_ != null)
        {
            this._aComandoSemCasam_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aComandoSemCasam_ = node;
    }

    public PAComandoCasam getAComandoCasam()
    {
        return this._aComandoCasam_;
    }

    public void setAComandoCasam(PAComandoCasam node)
    {
        if(this._aComandoCasam_ != null)
        {
            this._aComandoCasam_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._aComandoCasam_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._aExp_)
            + toString(this._aComandoSemCasam_)
            + toString(this._aComandoCasam_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._aExp_ == child)
        {
            this._aExp_ = null;
            return;
        }

        if(this._aComandoSemCasam_ == child)
        {
            this._aComandoSemCasam_ = null;
            return;
        }

        if(this._aComandoCasam_ == child)
        {
            this._aComandoCasam_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._aExp_ == oldChild)
        {
            setAExp((PAExp) newChild);
            return;
        }

        if(this._aComandoSemCasam_ == oldChild)
        {
            setAComandoSemCasam((PAComandoSemCasam) newChild);
            return;
        }

        if(this._aComandoCasam_ == oldChild)
        {
            setAComandoCasam((PAComandoCasam) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
