/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class AAtribOutras extends POutras
{
    private PAtrib _atrib_;
    private TPontoFinal _pontoFinal_;

    public AAtribOutras()
    {
        // Constructor
    }

    public AAtribOutras(
        @SuppressWarnings("hiding") PAtrib _atrib_,
        @SuppressWarnings("hiding") TPontoFinal _pontoFinal_)
    {
        // Constructor
        setAtrib(_atrib_);

        setPontoFinal(_pontoFinal_);

    }

    @Override
    public Object clone()
    {
        return new AAtribOutras(
            cloneNode(this._atrib_),
            cloneNode(this._pontoFinal_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAAtribOutras(this);
    }

    public PAtrib getAtrib()
    {
        return this._atrib_;
    }

    public void setAtrib(PAtrib node)
    {
        if(this._atrib_ != null)
        {
            this._atrib_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._atrib_ = node;
    }

    public TPontoFinal getPontoFinal()
    {
        return this._pontoFinal_;
    }

    public void setPontoFinal(TPontoFinal node)
    {
        if(this._pontoFinal_ != null)
        {
            this._pontoFinal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pontoFinal_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._atrib_)
            + toString(this._pontoFinal_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._atrib_ == child)
        {
            this._atrib_ = null;
            return;
        }

        if(this._pontoFinal_ == child)
        {
            this._pontoFinal_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._atrib_ == oldChild)
        {
            setAtrib((PAtrib) newChild);
            return;
        }

        if(this._pontoFinal_ == oldChild)
        {
            setPontoFinal((TPontoFinal) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
