/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class ACaractereTipoBase extends PTipoBase
{
    private TBaseCaractere _baseCaractere_;

    public ACaractereTipoBase()
    {
        // Constructor
    }

    public ACaractereTipoBase(
        @SuppressWarnings("hiding") TBaseCaractere _baseCaractere_)
    {
        // Constructor
        setBaseCaractere(_baseCaractere_);

    }

    @Override
    public Object clone()
    {
        return new ACaractereTipoBase(
            cloneNode(this._baseCaractere_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACaractereTipoBase(this);
    }

    public TBaseCaractere getBaseCaractere()
    {
        return this._baseCaractere_;
    }

    public void setBaseCaractere(TBaseCaractere node)
    {
        if(this._baseCaractere_ != null)
        {
            this._baseCaractere_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._baseCaractere_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._baseCaractere_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._baseCaractere_ == child)
        {
            this._baseCaractere_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._baseCaractere_ == oldChild)
        {
            setBaseCaractere((TBaseCaractere) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
