/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class ACasamComando extends PComando
{
    private PComandoCasam _comandoCasam_;

    public ACasamComando()
    {
        // Constructor
    }

    public ACasamComando(
        @SuppressWarnings("hiding") PComandoCasam _comandoCasam_)
    {
        // Constructor
        setComandoCasam(_comandoCasam_);

    }

    @Override
    public Object clone()
    {
        return new ACasamComando(
            cloneNode(this._comandoCasam_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseACasamComando(this);
    }

    public PComandoCasam getComandoCasam()
    {
        return this._comandoCasam_;
    }

    public void setComandoCasam(PComandoCasam node)
    {
        if(this._comandoCasam_ != null)
        {
            this._comandoCasam_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._comandoCasam_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._comandoCasam_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._comandoCasam_ == child)
        {
            this._comandoCasam_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._comandoCasam_ == oldChild)
        {
            setComandoCasam((PComandoCasam) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
