/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class AChamadaOutras extends POutras
{
    private PChamada _chamada_;
    private TPontoFinal _pontoFinal_;

    public AChamadaOutras()
    {
        // Constructor
    }

    public AChamadaOutras(
        @SuppressWarnings("hiding") PChamada _chamada_,
        @SuppressWarnings("hiding") TPontoFinal _pontoFinal_)
    {
        // Constructor
        setChamada(_chamada_);

        setPontoFinal(_pontoFinal_);

    }

    @Override
    public Object clone()
    {
        return new AChamadaOutras(
            cloneNode(this._chamada_),
            cloneNode(this._pontoFinal_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAChamadaOutras(this);
    }

    public PChamada getChamada()
    {
        return this._chamada_;
    }

    public void setChamada(PChamada node)
    {
        if(this._chamada_ != null)
        {
            this._chamada_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._chamada_ = node;
    }

    public TPontoFinal getPontoFinal()
    {
        return this._pontoFinal_;
    }

    public void setPontoFinal(TPontoFinal node)
    {
        if(this._pontoFinal_ != null)
        {
            this._pontoFinal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pontoFinal_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._chamada_)
            + toString(this._pontoFinal_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._chamada_ == child)
        {
            this._chamada_ = null;
            return;
        }

        if(this._pontoFinal_ == child)
        {
            this._pontoFinal_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._chamada_ == oldChild)
        {
            setChamada((PChamada) newChild);
            return;
        }

        if(this._pontoFinal_ == oldChild)
        {
            setPontoFinal((TPontoFinal) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
