/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class ADecCasamComando extends PComando
{
    private PDecCasam _decCasam_;

    public ADecCasamComando()
    {
        // Constructor
    }

    public ADecCasamComando(
        @SuppressWarnings("hiding") PDecCasam _decCasam_)
    {
        // Constructor
        setDecCasam(_decCasam_);

    }

    @Override
    public Object clone()
    {
        return new ADecCasamComando(
            cloneNode(this._decCasam_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADecCasamComando(this);
    }

    public PDecCasam getDecCasam()
    {
        return this._decCasam_;
    }

    public void setDecCasam(PDecCasam node)
    {
        if(this._decCasam_ != null)
        {
            this._decCasam_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._decCasam_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._decCasam_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._decCasam_ == child)
        {
            this._decCasam_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._decCasam_ == oldChild)
        {
            setDecCasam((PDecCasam) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
