/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class ADivExp10 extends PExp10
{
    private PExp10 _exp10_;
    private TDiv _div_;
    private PExp11 _exp11_;

    public ADivExp10()
    {
        // Constructor
    }

    public ADivExp10(
        @SuppressWarnings("hiding") PExp10 _exp10_,
        @SuppressWarnings("hiding") TDiv _div_,
        @SuppressWarnings("hiding") PExp11 _exp11_)
    {
        // Constructor
        setExp10(_exp10_);

        setDiv(_div_);

        setExp11(_exp11_);

    }

    @Override
    public Object clone()
    {
        return new ADivExp10(
            cloneNode(this._exp10_),
            cloneNode(this._div_),
            cloneNode(this._exp11_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseADivExp10(this);
    }

    public PExp10 getExp10()
    {
        return this._exp10_;
    }

    public void setExp10(PExp10 node)
    {
        if(this._exp10_ != null)
        {
            this._exp10_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp10_ = node;
    }

    public TDiv getDiv()
    {
        return this._div_;
    }

    public void setDiv(TDiv node)
    {
        if(this._div_ != null)
        {
            this._div_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._div_ = node;
    }

    public PExp11 getExp11()
    {
        return this._exp11_;
    }

    public void setExp11(PExp11 node)
    {
        if(this._exp11_ != null)
        {
            this._exp11_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp11_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp10_)
            + toString(this._div_)
            + toString(this._exp11_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp10_ == child)
        {
            this._exp10_ = null;
            return;
        }

        if(this._div_ == child)
        {
            this._div_ = null;
            return;
        }

        if(this._exp11_ == child)
        {
            this._exp11_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp10_ == oldChild)
        {
            setExp10((PExp10) newChild);
            return;
        }

        if(this._div_ == oldChild)
        {
            setDiv((TDiv) newChild);
            return;
        }

        if(this._exp11_ == oldChild)
        {
            setExp11((PExp11) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
