/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class AEExpOu extends PExpOu
{
    private PExpOu _expOu_;
    private TE _e_;
    private PExpE _expE_;

    public AEExpOu()
    {
        // Constructor
    }

    public AEExpOu(
        @SuppressWarnings("hiding") PExpOu _expOu_,
        @SuppressWarnings("hiding") TE _e_,
        @SuppressWarnings("hiding") PExpE _expE_)
    {
        // Constructor
        setExpOu(_expOu_);

        setE(_e_);

        setExpE(_expE_);

    }

    @Override
    public Object clone()
    {
        return new AEExpOu(
            cloneNode(this._expOu_),
            cloneNode(this._e_),
            cloneNode(this._expE_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEExpOu(this);
    }

    public PExpOu getExpOu()
    {
        return this._expOu_;
    }

    public void setExpOu(PExpOu node)
    {
        if(this._expOu_ != null)
        {
            this._expOu_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expOu_ = node;
    }

    public TE getE()
    {
        return this._e_;
    }

    public void setE(TE node)
    {
        if(this._e_ != null)
        {
            this._e_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._e_ = node;
    }

    public PExpE getExpE()
    {
        return this._expE_;
    }

    public void setExpE(PExpE node)
    {
        if(this._expE_ != null)
        {
            this._expE_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expE_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expOu_)
            + toString(this._e_)
            + toString(this._expE_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expOu_ == child)
        {
            this._expOu_ = null;
            return;
        }

        if(this._e_ == child)
        {
            this._e_ = null;
            return;
        }

        if(this._expE_ == child)
        {
            this._expE_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expOu_ == oldChild)
        {
            setExpOu((PExpOu) newChild);
            return;
        }

        if(this._e_ == oldChild)
        {
            setE((TE) newChild);
            return;
        }

        if(this._expE_ == oldChild)
        {
            setExpE((PExpE) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
