/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class AExpCmpExpIgual extends PExpIgual
{
    private PExpCmp _expCmp_;

    public AExpCmpExpIgual()
    {
        // Constructor
    }

    public AExpCmpExpIgual(
        @SuppressWarnings("hiding") PExpCmp _expCmp_)
    {
        // Constructor
        setExpCmp(_expCmp_);

    }

    @Override
    public Object clone()
    {
        return new AExpCmpExpIgual(
            cloneNode(this._expCmp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpCmpExpIgual(this);
    }

    public PExpCmp getExpCmp()
    {
        return this._expCmp_;
    }

    public void setExpCmp(PExpCmp node)
    {
        if(this._expCmp_ != null)
        {
            this._expCmp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expCmp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expCmp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expCmp_ == child)
        {
            this._expCmp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expCmp_ == oldChild)
        {
            setExpCmp((PExpCmp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
