/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class AExpEExpOu extends PExpOu
{
    private PExpE _expE_;

    public AExpEExpOu()
    {
        // Constructor
    }

    public AExpEExpOu(
        @SuppressWarnings("hiding") PExpE _expE_)
    {
        // Constructor
        setExpE(_expE_);

    }

    @Override
    public Object clone()
    {
        return new AExpEExpOu(
            cloneNode(this._expE_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpEExpOu(this);
    }

    public PExpE getExpE()
    {
        return this._expE_;
    }

    public void setExpE(PExpE node)
    {
        if(this._expE_ != null)
        {
            this._expE_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expE_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expE_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expE_ == child)
        {
            this._expE_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expE_ == oldChild)
        {
            setExpE((PExpE) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
