/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class AExpIgualExpE extends PExpE
{
    private PExpIgual _expIgual_;

    public AExpIgualExpE()
    {
        // Constructor
    }

    public AExpIgualExpE(
        @SuppressWarnings("hiding") PExpIgual _expIgual_)
    {
        // Constructor
        setExpIgual(_expIgual_);

    }

    @Override
    public Object clone()
    {
        return new AExpIgualExpE(
            cloneNode(this._expIgual_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExpIgualExpE(this);
    }

    public PExpIgual getExpIgual()
    {
        return this._expIgual_;
    }

    public void setExpIgual(PExpIgual node)
    {
        if(this._expIgual_ != null)
        {
            this._expIgual_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expIgual_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expIgual_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expIgual_ == child)
        {
            this._expIgual_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expIgual_ == oldChild)
        {
            setExpIgual((PExpIgual) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
