/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class AExp12 extends PExp12
{
    private PExp13 _exp13_;

    public AExp12()
    {
        // Constructor
    }

    public AExp12(
        @SuppressWarnings("hiding") PExp13 _exp13_)
    {
        // Constructor
        setExp13(_exp13_);

    }

    @Override
    public Object clone()
    {
        return new AExp12(
            cloneNode(this._exp13_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAExp12(this);
    }

    public PExp13 getExp13()
    {
        return this._exp13_;
    }

    public void setExp13(PExp13 node)
    {
        if(this._exp13_ != null)
        {
            this._exp13_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp13_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp13_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp13_ == child)
        {
            this._exp13_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp13_ == oldChild)
        {
            setExp13((PExp13) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
