/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class AIgualExpE extends PExpE
{
    private PExpE _expE_;
    private TIgual _igual_;
    private PExpIgual _expIgual_;

    public AIgualExpE()
    {
        // Constructor
    }

    public AIgualExpE(
        @SuppressWarnings("hiding") PExpE _expE_,
        @SuppressWarnings("hiding") TIgual _igual_,
        @SuppressWarnings("hiding") PExpIgual _expIgual_)
    {
        // Constructor
        setExpE(_expE_);

        setIgual(_igual_);

        setExpIgual(_expIgual_);

    }

    @Override
    public Object clone()
    {
        return new AIgualExpE(
            cloneNode(this._expE_),
            cloneNode(this._igual_),
            cloneNode(this._expIgual_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAIgualExpE(this);
    }

    public PExpE getExpE()
    {
        return this._expE_;
    }

    public void setExpE(PExpE node)
    {
        if(this._expE_ != null)
        {
            this._expE_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expE_ = node;
    }

    public TIgual getIgual()
    {
        return this._igual_;
    }

    public void setIgual(TIgual node)
    {
        if(this._igual_ != null)
        {
            this._igual_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._igual_ = node;
    }

    public PExpIgual getExpIgual()
    {
        return this._expIgual_;
    }

    public void setExpIgual(PExpIgual node)
    {
        if(this._expIgual_ != null)
        {
            this._expIgual_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expIgual_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expE_)
            + toString(this._igual_)
            + toString(this._expIgual_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expE_ == child)
        {
            this._expE_ = null;
            return;
        }

        if(this._igual_ == child)
        {
            this._igual_ = null;
            return;
        }

        if(this._expIgual_ == child)
        {
            this._expIgual_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expE_ == oldChild)
        {
            setExpE((PExpE) newChild);
            return;
        }

        if(this._igual_ == oldChild)
        {
            setIgual((TIgual) newChild);
            return;
        }

        if(this._expIgual_ == oldChild)
        {
            setExpIgual((PExpIgual) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
