/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import java.util.*;
import caju.analysis.*;

@SuppressWarnings("nls")
public final class AListaAtrib extends PListaAtrib
{
    private PAtrib _atrib_;
    private final LinkedList<PVirgulaAtrib> _virgulaAtrib_ = new LinkedList<PVirgulaAtrib>();

    public AListaAtrib()
    {
        // Constructor
    }

    public AListaAtrib(
        @SuppressWarnings("hiding") PAtrib _atrib_,
        @SuppressWarnings("hiding") List<?> _virgulaAtrib_)
    {
        // Constructor
        setAtrib(_atrib_);

        setVirgulaAtrib(_virgulaAtrib_);

    }

    @Override
    public Object clone()
    {
        return new AListaAtrib(
            cloneNode(this._atrib_),
            cloneList(this._virgulaAtrib_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAListaAtrib(this);
    }

    public PAtrib getAtrib()
    {
        return this._atrib_;
    }

    public void setAtrib(PAtrib node)
    {
        if(this._atrib_ != null)
        {
            this._atrib_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._atrib_ = node;
    }

    public LinkedList<PVirgulaAtrib> getVirgulaAtrib()
    {
        return this._virgulaAtrib_;
    }

    public void setVirgulaAtrib(List<?> list)
    {
        for(PVirgulaAtrib e : this._virgulaAtrib_)
        {
            e.parent(null);
        }
        this._virgulaAtrib_.clear();

        for(Object obj_e : list)
        {
            PVirgulaAtrib e = (PVirgulaAtrib) obj_e;
            if(e.parent() != null)
            {
                e.parent().removeChild(e);
            }

            e.parent(this);
            this._virgulaAtrib_.add(e);
        }
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._atrib_)
            + toString(this._virgulaAtrib_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._atrib_ == child)
        {
            this._atrib_ = null;
            return;
        }

        if(this._virgulaAtrib_.remove(child))
        {
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._atrib_ == oldChild)
        {
            setAtrib((PAtrib) newChild);
            return;
        }

        for(ListIterator<PVirgulaAtrib> i = this._virgulaAtrib_.listIterator(); i.hasNext();)
        {
            if(i.next() == oldChild)
            {
                if(newChild != null)
                {
                    i.set((PVirgulaAtrib) newChild);
                    newChild.parent(this);
                    oldChild.parent(null);
                    return;
                }

                i.remove();
                oldChild.parent(null);
                return;
            }
        }

        throw new RuntimeException("Not a child.");
    }
}
