/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class AMaiorMenorExpIgual extends PExpIgual
{
    private PExpIgual _expIgual_;
    private POperadorRelacional _operadorRelacional_;
    private PExpCmp _expCmp_;

    public AMaiorMenorExpIgual()
    {
        // Constructor
    }

    public AMaiorMenorExpIgual(
        @SuppressWarnings("hiding") PExpIgual _expIgual_,
        @SuppressWarnings("hiding") POperadorRelacional _operadorRelacional_,
        @SuppressWarnings("hiding") PExpCmp _expCmp_)
    {
        // Constructor
        setExpIgual(_expIgual_);

        setOperadorRelacional(_operadorRelacional_);

        setExpCmp(_expCmp_);

    }

    @Override
    public Object clone()
    {
        return new AMaiorMenorExpIgual(
            cloneNode(this._expIgual_),
            cloneNode(this._operadorRelacional_),
            cloneNode(this._expCmp_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMaiorMenorExpIgual(this);
    }

    public PExpIgual getExpIgual()
    {
        return this._expIgual_;
    }

    public void setExpIgual(PExpIgual node)
    {
        if(this._expIgual_ != null)
        {
            this._expIgual_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expIgual_ = node;
    }

    public POperadorRelacional getOperadorRelacional()
    {
        return this._operadorRelacional_;
    }

    public void setOperadorRelacional(POperadorRelacional node)
    {
        if(this._operadorRelacional_ != null)
        {
            this._operadorRelacional_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._operadorRelacional_ = node;
    }

    public PExpCmp getExpCmp()
    {
        return this._expCmp_;
    }

    public void setExpCmp(PExpCmp node)
    {
        if(this._expCmp_ != null)
        {
            this._expCmp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expCmp_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expIgual_)
            + toString(this._operadorRelacional_)
            + toString(this._expCmp_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expIgual_ == child)
        {
            this._expIgual_ = null;
            return;
        }

        if(this._operadorRelacional_ == child)
        {
            this._operadorRelacional_ = null;
            return;
        }

        if(this._expCmp_ == child)
        {
            this._expCmp_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expIgual_ == oldChild)
        {
            setExpIgual((PExpIgual) newChild);
            return;
        }

        if(this._operadorRelacional_ == oldChild)
        {
            setOperadorRelacional((POperadorRelacional) newChild);
            return;
        }

        if(this._expCmp_ == oldChild)
        {
            setExpCmp((PExpCmp) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
