/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class AMultExp9 extends PExp9
{
    private PExp9 _exp9_;
    private TMult _mult_;
    private PExp10 _exp10_;

    public AMultExp9()
    {
        // Constructor
    }

    public AMultExp9(
        @SuppressWarnings("hiding") PExp9 _exp9_,
        @SuppressWarnings("hiding") TMult _mult_,
        @SuppressWarnings("hiding") PExp10 _exp10_)
    {
        // Constructor
        setExp9(_exp9_);

        setMult(_mult_);

        setExp10(_exp10_);

    }

    @Override
    public Object clone()
    {
        return new AMultExp9(
            cloneNode(this._exp9_),
            cloneNode(this._mult_),
            cloneNode(this._exp10_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultExp9(this);
    }

    public PExp9 getExp9()
    {
        return this._exp9_;
    }

    public void setExp9(PExp9 node)
    {
        if(this._exp9_ != null)
        {
            this._exp9_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp9_ = node;
    }

    public TMult getMult()
    {
        return this._mult_;
    }

    public void setMult(TMult node)
    {
        if(this._mult_ != null)
        {
            this._mult_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._mult_ = node;
    }

    public PExp10 getExp10()
    {
        return this._exp10_;
    }

    public void setExp10(PExp10 node)
    {
        if(this._exp10_ != null)
        {
            this._exp10_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp10_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._exp9_)
            + toString(this._mult_)
            + toString(this._exp10_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._exp9_ == child)
        {
            this._exp9_ = null;
            return;
        }

        if(this._mult_ == child)
        {
            this._mult_ = null;
            return;
        }

        if(this._exp10_ == child)
        {
            this._exp10_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._exp9_ == oldChild)
        {
            setExp9((PExp9) newChild);
            return;
        }

        if(this._mult_ == oldChild)
        {
            setMult((TMult) newChild);
            return;
        }

        if(this._exp10_ == oldChild)
        {
            setExp10((PExp10) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
