/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class AMultiplicacaoDivisaoExpTermo extends PExpTermo
{
    private PExpTermo _expTermo_;
    private PMultDiv _multDiv_;
    private PExpNao _expNao_;

    public AMultiplicacaoDivisaoExpTermo()
    {
        // Constructor
    }

    public AMultiplicacaoDivisaoExpTermo(
        @SuppressWarnings("hiding") PExpTermo _expTermo_,
        @SuppressWarnings("hiding") PMultDiv _multDiv_,
        @SuppressWarnings("hiding") PExpNao _expNao_)
    {
        // Constructor
        setExpTermo(_expTermo_);

        setMultDiv(_multDiv_);

        setExpNao(_expNao_);

    }

    @Override
    public Object clone()
    {
        return new AMultiplicacaoDivisaoExpTermo(
            cloneNode(this._expTermo_),
            cloneNode(this._multDiv_),
            cloneNode(this._expNao_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAMultiplicacaoDivisaoExpTermo(this);
    }

    public PExpTermo getExpTermo()
    {
        return this._expTermo_;
    }

    public void setExpTermo(PExpTermo node)
    {
        if(this._expTermo_ != null)
        {
            this._expTermo_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expTermo_ = node;
    }

    public PMultDiv getMultDiv()
    {
        return this._multDiv_;
    }

    public void setMultDiv(PMultDiv node)
    {
        if(this._multDiv_ != null)
        {
            this._multDiv_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._multDiv_ = node;
    }

    public PExpNao getExpNao()
    {
        return this._expNao_;
    }

    public void setExpNao(PExpNao node)
    {
        if(this._expNao_ != null)
        {
            this._expNao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._expNao_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._expTermo_)
            + toString(this._multDiv_)
            + toString(this._expNao_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._expTermo_ == child)
        {
            this._expTermo_ = null;
            return;
        }

        if(this._multDiv_ == child)
        {
            this._multDiv_ = null;
            return;
        }

        if(this._expNao_ == child)
        {
            this._expNao_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._expTermo_ == oldChild)
        {
            setExpTermo((PExpTermo) newChild);
            return;
        }

        if(this._multDiv_ == oldChild)
        {
            setMultDiv((PMultDiv) newChild);
            return;
        }

        if(this._expNao_ == oldChild)
        {
            setExpNao((PExpNao) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
