/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class ANaoExp11 extends PExp11
{
    private TNao _nao_;
    private PExp12 _exp12_;

    public ANaoExp11()
    {
        // Constructor
    }

    public ANaoExp11(
        @SuppressWarnings("hiding") TNao _nao_,
        @SuppressWarnings("hiding") PExp12 _exp12_)
    {
        // Constructor
        setNao(_nao_);

        setExp12(_exp12_);

    }

    @Override
    public Object clone()
    {
        return new ANaoExp11(
            cloneNode(this._nao_),
            cloneNode(this._exp12_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANaoExp11(this);
    }

    public TNao getNao()
    {
        return this._nao_;
    }

    public void setNao(TNao node)
    {
        if(this._nao_ != null)
        {
            this._nao_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._nao_ = node;
    }

    public PExp12 getExp12()
    {
        return this._exp12_;
    }

    public void setExp12(PExp12 node)
    {
        if(this._exp12_ != null)
        {
            this._exp12_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp12_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._nao_)
            + toString(this._exp12_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._nao_ == child)
        {
            this._nao_ = null;
            return;
        }

        if(this._exp12_ == child)
        {
            this._exp12_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._nao_ == oldChild)
        {
            setNao((TNao) newChild);
            return;
        }

        if(this._exp12_ == oldChild)
        {
            setExp12((PExp12) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
