/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class ANumeroTipoBase extends PTipoBase
{
    private TBaseNumero _baseNumero_;

    public ANumeroTipoBase()
    {
        // Constructor
    }

    public ANumeroTipoBase(
        @SuppressWarnings("hiding") TBaseNumero _baseNumero_)
    {
        // Constructor
        setBaseNumero(_baseNumero_);

    }

    @Override
    public Object clone()
    {
        return new ANumeroTipoBase(
            cloneNode(this._baseNumero_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseANumeroTipoBase(this);
    }

    public TBaseNumero getBaseNumero()
    {
        return this._baseNumero_;
    }

    public void setBaseNumero(TBaseNumero node)
    {
        if(this._baseNumero_ != null)
        {
            this._baseNumero_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._baseNumero_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._baseNumero_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._baseNumero_ == child)
        {
            this._baseNumero_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._baseNumero_ == oldChild)
        {
            setBaseNumero((TBaseNumero) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
