/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class AOutraComando extends PComando
{
    private POutras _outras_;

    public AOutraComando()
    {
        // Constructor
    }

    public AOutraComando(
        @SuppressWarnings("hiding") POutras _outras_)
    {
        // Constructor
        setOutras(_outras_);

    }

    @Override
    public Object clone()
    {
        return new AOutraComando(
            cloneNode(this._outras_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAOutraComando(this);
    }

    public POutras getOutras()
    {
        return this._outras_;
    }

    public void setOutras(POutras node)
    {
        if(this._outras_ != null)
        {
            this._outras_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._outras_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._outras_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._outras_ == child)
        {
            this._outras_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._outras_ == oldChild)
        {
            setOutras((POutras) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
