/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class ARetorneComandoSemCasam extends PComandoSemCasam
{
    private TRetorne _retorne_;
    private PExp _exp_;
    private TPontoFinal _pontoFinal_;

    public ARetorneComandoSemCasam()
    {
        // Constructor
    }

    public ARetorneComandoSemCasam(
        @SuppressWarnings("hiding") TRetorne _retorne_,
        @SuppressWarnings("hiding") PExp _exp_,
        @SuppressWarnings("hiding") TPontoFinal _pontoFinal_)
    {
        // Constructor
        setRetorne(_retorne_);

        setExp(_exp_);

        setPontoFinal(_pontoFinal_);

    }

    @Override
    public Object clone()
    {
        return new ARetorneComandoSemCasam(
            cloneNode(this._retorne_),
            cloneNode(this._exp_),
            cloneNode(this._pontoFinal_));
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseARetorneComandoSemCasam(this);
    }

    public TRetorne getRetorne()
    {
        return this._retorne_;
    }

    public void setRetorne(TRetorne node)
    {
        if(this._retorne_ != null)
        {
            this._retorne_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._retorne_ = node;
    }

    public PExp getExp()
    {
        return this._exp_;
    }

    public void setExp(PExp node)
    {
        if(this._exp_ != null)
        {
            this._exp_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._exp_ = node;
    }

    public TPontoFinal getPontoFinal()
    {
        return this._pontoFinal_;
    }

    public void setPontoFinal(TPontoFinal node)
    {
        if(this._pontoFinal_ != null)
        {
            this._pontoFinal_.parent(null);
        }

        if(node != null)
        {
            if(node.parent() != null)
            {
                node.parent().removeChild(node);
            }

            node.parent(this);
        }

        this._pontoFinal_ = node;
    }

    @Override
    public String toString()
    {
        return ""
            + toString(this._retorne_)
            + toString(this._exp_)
            + toString(this._pontoFinal_);
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        if(this._retorne_ == child)
        {
            this._retorne_ = null;
            return;
        }

        if(this._exp_ == child)
        {
            this._exp_ = null;
            return;
        }

        if(this._pontoFinal_ == child)
        {
            this._pontoFinal_ = null;
            return;
        }

        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        if(this._retorne_ == oldChild)
        {
            setRetorne((TRetorne) newChild);
            return;
        }

        if(this._exp_ == oldChild)
        {
            setExp((PExp) newChild);
            return;
        }

        if(this._pontoFinal_ == oldChild)
        {
            setPontoFinal((TPontoFinal) newChild);
            return;
        }

        throw new RuntimeException("Not a child.");
    }
}
