/* This file was generated by SableCC (http://www.sablecc.org/). */

package caju.node;

import caju.analysis.*;

@SuppressWarnings("nls")
public final class AVazioExp13 extends PExp13
{

    public AVazioExp13()
    {
        // Constructor
    }

    @Override
    public Object clone()
    {
        return new AVazioExp13();
    }

    @Override
    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAVazioExp13(this);
    }

    @Override
    public String toString()
    {
        return "";
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        throw new RuntimeException("Not a child.");
    }
}
